workflows:
  osmacard_maui:
    name: "OsmaCard .NET MAUI Build"
    max_build_duration: 60

    environment:
      vars:
        PROJECT_PATH: "OsmaCard.csproj"
        BUILD_CONFIGURATION: "Release"
      xcode: latest
      groups:
        - ios_credentials
        - android_keystore

    scripts:

      # -------------------------------------------------------------
      # INSTALL .NET 8 (MAUI NON SUPPORTA .NET 9/10 SU CODENAMIC)
      # -------------------------------------------------------------
      - name: Install .NET 8 SDK
        script: |
          curl -L https://download.visualstudio.microsoft.com/download/pr/34b44a6c-33b0-4d3d-b694-0a9eecdccb9e/5a1f89e2a9b419add4ef95c0d37db114/dotnet-sdk-8.0.404-osx-arm64.pkg -o dotnet8.pkg
          sudo installer -pkg dotnet8.pkg -target /
          export PATH="/usr/local/share/dotnet:$PATH"
          dotnet --version

      # -------------------------------------------------------------
      # INSTALL MAUI WORKLOADS NECESSARI
      # -------------------------------------------------------------
      - name: Install MAUI workloads
        script: |
          export PATH="/usr/local/share/dotnet:$PATH"

          dotnet workload install mau
