workflows:
  android_maui:
    name: "OsmaCard .NET MAUI Android Build"
    max_build_duration: 30

    environment:
      platforms:
        - linux
      vars:
        PROJECT_PATH: "OsmaCard.csproj"
        BUILD_CONFIGURATION: "Release"

    cache:
      cache_paths:
        - $HOME/.nuget/packages
        - $HOME/.dotnet
        - $HOME/.dotnet/tools

    scripts:

      # -------------------------------------------------------------
      # INSTALL .NET 8 SDK (Linux)
      # -------------------------------------------------------------
      - name: Install .NET 8 SDK
        script: |
          mkdir -p $HOME/dotnet
          curl -L https://dotnet.microsoft.com/download/dotnet/thank-you/sdk-8.0.100-linux-x64-binaries -o dotnet.tar.gz
          tar -xzf dotnet.tar.gz -C $HOME/dotnet
          export PATH="$HOME/dotnet:$PATH"
          export DOTNET_ROOT="$HOME/dotnet"
          dotnet --version

      # -------------------------------------------------------------
      # INSTALL WORKLOADS MAUI + ANDROID
      # -------------------------------------------------------------
      - name: Install workloads
        script: |
          export PATH="$HOME/dotnet:$PATH"
          export DOTNET_ROOT="$HOME/dotnet"

          dotnet workload install maui
          dotnet workload install android
          dotnet workload restore
          dotnet workload list

      # -------------------------------------------------------------
      # RESTORE NUGET PACKAGES
      # -------------------------------------------------------------
      - name: Restore NuGet packages
        script: |
          export PATH="$HOME/dotnet:$PATH"
          dotnet restore $PROJECT_PATH

      # -------------------------------------------------------------
      # BUILD ANDROID APK/AAB
      # -------------------------------------------------------------
      - name: Build Android APK
        script: |
          export PATH="$HOME/dotnet:$PATH"

          dotnet build $PROJECT_PATH \
            -c $BUILD_CONFIGURATION \
            -f net8.0-android \
            -p:AndroidSigningKeyStore=$CM_KEYSTORE_PATH \
            -p:Andr
